### ISSUE TITLE
Roadmap: v0.7

### ISSUE THREAD

**Issue by nickgermaine** [liri-project/liri-vinyl#1]
Roadmap to v0.7
Idea: Prettify the core functionality, so that it serves a basic media players use.
- [x] Album Tiles (instead of list)
- [ ] Artist Images (maybe scrape from wikipedia or other CC sources if possible)
- [x] Multi threading where possible/logical
- [x] Make initial scan happen parallel to application (see multi threading)
- [x] The initial scan, and scanning files has trouble with certain languages.  I've got japanese music in my music folder, and it doesn't appear to be getting into the database because of the japanese characters.
- [ ] Add ability to re-scan/update music from within the app, with indeterminate progress popup, auto-reload after scan completes.

**Comment by IdrissDimson** [comment]
You should also add on the list an update to Qt 5.6
